# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/564170e3-921d-46da-91c3-7287272ffc91";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D0D5-BE1B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # PopOS drive
  fileSystems."/run/media/matt/4578532b-0faa-44cc-b0fb-ce0991329478" =
  {  device = "/dev/disk/by-uuid/4578532b-0faa-44cc-b0fb-ce0991329478";
     fsType = "ext4";
  };

  # Ubuntu drive
  fileSystems."/run/media/matt/71cbd99d-c718-4101-9063-8a9a6bfb8c10" =
  {  device = "/dev/disk/by-uuid/71cbd99d-c718-4101-9063-8a9a6bfb8c10";
     fsType = "ext4";
  };
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
